<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Reports Export</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 12px;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h2 {
            margin: 0;
            color: #dc2626;
        }
        .date {
            text-align: right;
            font-size: 10px;
            margin-bottom: 15px;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th, td {
            border: 1px solid #ccc;
            padding: 6px 8px;
            text-align: left;
            vertical-align: top;
        }
        th {
            background-color: #f5f5f5;
            font-weight: bold;
            font-size: 11px;
        }
        td {
            font-size: 10px;
        }
        .text-center {
            text-align: center;
        }
        .text-right {
            text-align: right;
        }
        .badge {
            display: inline-block;
            padding: 2px 6px;
            border-radius: 12px;
            font-size: 9px;
            font-weight: bold;
        }
        /* Optional: status colors */
        .status-pending { color: #b45309; }
        .status-resolved { color: #15803d; }
        .footer {
            margin-top: 20px;
            font-size: 9px;
            text-align: center;
            color: #888;
        }
    </style>
</head>
<body>
    <div class="header">
        <h2>Emergency Reports</h2>
    </div>
    <div class="date">
        Exported on: {{ now()->format('Y-m-d H:i') }}
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Citizen</th>
                <th>Type</th>
                <th>Title</th>
                <th>Location</th>
                <th>Status</th>
                <th>Submitted</th>
                <th>Station</th>
            </thead>
        <tbody>
            @foreach($reports as $report)
            <tr>
                <td class="text-center">{{ $report->id }}</td>
                <td>{{ $report->reporter->name ?? 'Unknown' }}</td>
                <td>{{ ucfirst($report->type) }}</td>
                <td>{{ $report->title }}</td>
                <td>{{ $report->location }}</td>
                <td>{{ ucfirst($report->status) }}</td>
                <td class="text-center">{{ $report->created_at->format('Y-m-d H:i') }}</td>
                <td>{{ $report->station->name ?? '—' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by Emergency Response System
    </div>
</body>
</html>